# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('old_data_json', models.JSONField(blank=True, default=dict)),
                ('new_data_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='auditlog_au_organiz_8ea603_idx'), models.Index(fields=['organization', 'action'], name='auditlog_au_organiz_9666db_idx'), models.Index(fields=['entity_type', 'entity_id'], name='auditlog_au_entity__aa947c_idx')],
            },
        ),
    ]
