# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('vendor_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('expiry_warning', 'Expiry Warning'), ('expiry_overdue', 'Expiry Overdue')], max_length=30)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='organizations.organization')),
                ('vendor_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vendor_documents.vendordocument')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='expiries_re_organiz_e8c415_idx'), models.Index(fields=['organization', 'scheduled_for'], name='expiries_re_organiz_0fb8c9_idx')],
            },
        ),
    ]
