.PHONY: dev migrate makemigrations createsuperuser test

dev:
\tpython manage.py runserver 0.0.0.0:8000

makemigrations:
\tpython manage.py makemigrations

migrate:
\tpython manage.py migrate

createsuperuser:
\tpython manage.py createsuperuser

test:
\tpytest