# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=255)),
                ('template_code', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='notificatio_organiz_247fa6_idx'), models.Index(fields=['organization', 'sent_at'], name='notificatio_organiz_7e042b_idx')],
            },
        ),
    ]
