export const APP_ROUTES = {
  dashboard: "/app/dashboard",
  vendors: "/app/vendors",
  onboarding: "/app/onboarding",
  documents: "/app/documents",
  approvals: "/app/approvals",
  expiriesUpcoming: "/app/expiries/upcoming",
  expiriesOverdue: "/app/expiries/overdue",
  expiriesRenewals: "/app/expiries/renewals",
  tasks: "/app/tasks",
  audit: "/app/audit",
  settings: "/app/settings",
  documentTypes: "/app/settings/document-types",
  templates: "/app/settings/templates",
  approvalFlows: "/app/settings/approval-flows",
  notifications: "/app/settings/notifications",
  organization: "/app/settings/organization",
  members: "/app/settings/members",
} as const;
