# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('onboarding_status', models.CharField(choices=[('draft', 'Draft'), ('documents_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('restricted', 'Restricted'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('operational_status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('restricted', 'Restricted'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='organizations.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'onboarding_status'], name='vendors_ven_organiz_3f589b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'operational_status'], name='vendors_ven_organiz_d348b6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'created_at'], name='vendors_ven_organiz_b63a7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('organization', 'vendor_code')},
        ),
        migrations.AddIndex(
            model_name='vendorcontact',
            index=models.Index(fields=['vendor', 'is_primary'], name='vendors_ven_vendor__7ee245_idx'),
        ),
    ]
