# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveIntegerField()),
                ('role_required', models.CharField(max_length=50)),
                ('decision_type', models.CharField(default='single', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('explicit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalflow')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('onboarding_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='onboarding.onboardingcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='organizations.organization')),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['organization', 'active'], name='approvals_a_organiz_9a3b88_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['organization', 'scope'], name='approvals_a_organiz_c5663e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['flow', 'step_order'], name='approvals_a_flow_id_bbef10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('flow', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['organization', 'decision'], name='approvals_a_organiz_2b2774_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['organization', 'created_at'], name='approvals_a_organiz_55783e_idx'),
        ),
    ]
