# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('has_expiry', models.BooleanField(default=False)),
                ('expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('applies_to_vendor_type', models.CharField(blank=True, max_length=100)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'category'], name='document_ty_organiz_ef7bd0_idx'), models.Index(fields=['organization', 'is_mandatory'], name='document_ty_organiz_114373_idx'), models.Index(fields=['organization', 'has_expiry'], name='document_ty_organiz_9ebb57_idx')],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
