# Generated by Django 5.2.13 on 2026-04-08 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_types', '0001_initial'),
        ('organizations', '0001_initial'),
        ('vendor_documents', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('applies_to_vendor_category', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('collecting_documents', 'Collecting Documents'), ('under_review', 'Under Review'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='not_started', max_length=30)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_cases', to='organizations.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_cases', to='vendors.vendor')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='onboarding.onboardingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTemplateRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('review_required', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_requirements', to='document_types.documenttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='onboarding.onboardingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required', models.BooleanField(default=True)),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='onboarding.onboardingcase')),
                ('current_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requirements', to='vendor_documents.vendordocument')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_types.documenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'status'], name='onboarding__case_id_b6bbf0_idx'), models.Index(fields=['case', 'required'], name='onboarding__case_id_f7cff6_idx')],
                'unique_together': {('case', 'document_type')},
            },
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['organization', 'active'], name='onboarding__organiz_ecc4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['organization', 'created_at'], name='onboarding__organiz_dedbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingcase',
            index=models.Index(fields=['organization', 'status'], name='onboarding__organiz_eba575_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingcase',
            index=models.Index(fields=['organization', 'created_at'], name='onboarding__organiz_6f6aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingcase',
            index=models.Index(fields=['organization', 'vendor'], name='onboarding__organiz_a18027_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplaterequirement',
            index=models.Index(fields=['template', 'sequence'], name='onboarding__templat_dd20cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtemplaterequirement',
            unique_together={('template', 'document_type')},
        ),
    ]
