# Generated by Django 5.2.13 on 2026-04-09 15:45

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(
                choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')],
                default='trial',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_2b8f9c_idx'),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('procurement_manager', 'Procurement Manager'), ('reviewer', 'Reviewer'), ('approver', 'Approver'), ('compliance_manager', 'Compliance Manager'), ('read_only', 'Read Only')], max_length=50)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['organization', 'status'], name='organizatio_organiz_9a9e64_idx'),
                    models.Index(fields=['email'], name='organizatio_email_31b01f_idx'),
                    models.Index(fields=['expires_at'], name='organizatio_expires_2bbf4a_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetupProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('members_invited', models.BooleanField(default=False)),
                ('vendor_categories_configured', models.BooleanField(default=False)),
                ('document_types_configured', models.BooleanField(default=False)),
                ('onboarding_templates_configured', models.BooleanField(default=False)),
                ('approval_flow_configured', models.BooleanField(default=False)),
                ('notifications_configured', models.BooleanField(default=False)),
                ('setup_completed', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to='organizations.organization')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['setup_completed'], name='organizatio_setup_c2dc75_idx'),
                ],
            },
        ),
    ]
